const images = {
    usertype: require('../assests/teacher.png'),
    user : require('../assests/user.png'),
    call : require('../assests/call.png'),
    institute : require('../assests/Institute.png'),
    Otpscreen : require('../assests/image.png'),
    backicon : require('../assests/back.png'),
    Qrcode : require('../assests/QRcode.png'),
    Notification : require('../assests/notification.png'),
    Plus : require('../assests/plus.png'),
    global : require('../assests/Global.png'),
    postdetail : require('../assests/postdetail.png'),
    like : require('../assests/like.png'),
    share : require('../assests/share.png'),
    comments : require('../assests/comment.png'),
    RightArrow : require('../assests/Arrow-Right.png'),
    liveclass : require('../assests/liveclass.png'),
    Studymaterial : require('../assests/studymaterial.png'),
    submithomework : require('../assests/homework.png'),
    Batchintro1 : require('../assests/batch.png'),
    Batchintro2 : require('../assests/batchintro2.png'),
    Batchintro3 : require('../assests/batchintro3.png'),
    Nobacth : require('../assests/nobatches.png'),
    editicon : require('../assests/editicon.png'),
    settings : require('../assests/settings.png'),
    mail : require('../assests/mail.png'),
    rollno :require('../assests/rollnumber.png'),
    datepicker : require('../assests/date.png'),
    address : require('../assests/location.png'),
    notfound : require('../assests/notfound.png'),
    download : require('../assests/Download.png'),
    time : require('../assests/time.png'),
    datecard : require('../assests/datecard.png'),
    liveicon : require('../assests/liveicon.png'),
    livedate : require('../assests/livedate.png'),
    liveclock : require('../assests/liveclock.png'),
    liveimg : require('../assests/liveimag.png'),
    pdffile : require('../assests/pdf.png'),
    jpgfile : require('../assests/jpg.png'),
    zipfile : require('../assests/zip.png'),
    smshare : require('../assests/smshare.png'),
    smdownload : require('../assests/smdownload.png'),
    ovbatches : require('../assests/ovbatches.png'),
    ovqrcode : require('../assests/ovqrcode.png'),
    ovwbatch : require('../assests/ovwbatches.png'),
    payfees : require('../assests/payFees.png'),
    testdownload : require('../assests/testdownload.png'),
    settingsarrow : require('../assests/setting.png'),
    privacypolicy : require('../assests/settingspp.png'),
    temrs : require('../assests/settingsterms.png'),
    help : require('../assests/settingshelp.png'),
    settingsprofile : require('../assests/settingsprofile.png'),
    Batch1 : require('../assests/Batch1.png'),
    Batch2 : require('../assests/Batch2.png'),
    SearchIcon : require('../assests/searchicon.png'),
    notice1 :require('../assests/notice1.png'),
    notice2 : require('../assests/notice2.png'),
    ChatProfile1 : require('../assests/ChatPro1.png'),
    Active:require('../assests/Active.png')

  }
  
  export default images